blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_index, name='index'),
    path('<int:pk>/', views.blog_detail, name='blog-detail'),
    path('<category>/', views.blog_category, name='blog-category'),
]

projects/urls.py
from django.urls import path

from projects import views

app_name = 'projects'
urlpatterns = [
    path('', views.projects, name='index'),
    path('<int:pk>/', views.project, name='project-detail'),
]

blog/models.py
from django.db import models
from django.urls import reverse

from config.settings.common import AUTH_USER_MODEL


class Category(models.Model):
    """
    Model for blog `Post` `Catagory`s.
    """
    name = models.CharField(
        max_length=20,
        verbose_name='Word to describe the Category',
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Date the Category was created',
    )

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    Model for blog `Post`s.
    """
    title = models.CharField(
        max_length=100,
        verbose_name='Title of the Post',
    )
    body = models.TextField(
        verbose_name='Body of the Post',
    )
    date_posted = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Date the Post was posted',
    )
    author = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Author of the Post',
    )
    categories = models.ManyToManyField(
        Category,
        related_name='posts',
        blank=True,
    )

    def __str__(self):
        return self.title

    def display_categories(self):
        """
        Returns a comma-separated list of `Category` names.
        """
        return ', '.join([category.name for category in self.categories.all()[:4]])

    display_categories.short_description = 'Categories'

    def get_absolute_url(self):
        """
        Returns the url to access a particular `Post` instance.
        """
        return reverse('blog:blog-detail', args=[str(self.id)])

class Comment(models.Model):
    """
    Model for blog `Post` `Comment`s.
    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.CharField(
        max_length=60,
    )
    # author = models.ForeignKey(
    #     AUTH_USER_MODEL,
    #     on_delete=models.CASCADE,
    # )
    body = models.TextField()
    date_posted = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return self.body[:20]

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Your Name"
            }
        )
    )
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Leave a comment!"
            }
        )
    )

blog/views.py
from django.shortcuts import render, redirect

from config.settings.common import THE_SITE_NAME
from blog.models import Post, Comment
from blog.forms import CommentForm


def blog_index(request):
    """
    View for the `blog.Blog` list view.
    """
    posts = Post.objects.all().order_by('-date_posted')
    context = {
        'the_site_name': THE_SITE_NAME,
        'page_title': 'Blog',
        'posts': posts,
    }
    return render(request, 'blog/blog_index.html', context)


def blog_category(request, category):
    """
    View for the `blog.Blog` list view filtered by `category`.
    """
    posts = Post.objects.filter(
        categories__name__icontains=category
    ).order_by(
        '-date_posted'
    )
    context = {
        'the_site_name': THE_SITE_NAME,
        'page_title': 'Blog',
        'category': category,
        'posts': posts,
    }
    return render(request, 'blog/blog_category.html', context)


def blog_detail(request, pk):
    """
    View for the `blog.Blog` detail view.
    """
    post = Post.objects.get(pk=pk)

    form = CommentForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()
            return redirect('blog:blog-detail', pk=post.pk)

    comments = Comment.objects.filter(post=post)
    context = {
        'the_site_name': THE_SITE_NAME,
        'page_title': 'Blog',
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'blog/blog_detail.html', context)

blog/templates/blog/blog_category.html
{% extends "base.html" %}

{% block title %}
    {{ the_site_name }}
    -
    {{ page_title }}
{% endblock title %}

{% block the_navbar %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'projects:index' %}">Projects</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
    </li>

    {% if user.is_authenticated %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'profile' user.id %}">Profile</a>
    </li>
    <li class="dropdown-divider"></li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}

{% endblock the_navbar %}

{% block content %}
    <div class="col-md-8 offset-md-2">
        <h1>{{ category | title }}</h1>
        <hr>
        {% for post in posts %}
            <h2><a href="{% url 'blog:blog-detail' post.pk%}">{{ post.title }}</a></h2>
            <small>
                {{ post.date_posted.date }} |&nbsp;
                {{ post.author }} |&nbsp;
                Categories:&nbsp;
                {% for category in post.categories.all %}
                <a href="{% url 'blog:blog-category' category.name %}">
                    {{ category.name }}
                </a>&nbsp;
                {% endfor %}
            </small>
            <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% block title %}
    {{ the_site_name }}
    -
    {{ post.title }}
{% endblock title %}

{% block the_navbar %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'projects:index' %}">Projects</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
    </li>

    {% if user.is_authenticated %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'profile' user.id %}">Profile</a>
    </li>
    <li class="dropdown-divider"></li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}

{% endblock the_navbar %}

{% block content %}
    <div class="col-md-8 offset-md-2">
        <h1>{{ post.title }}</h1>
        <small>
            {{ post.date_posted.date }} |&nbsp;
            {{ post.author }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:blog-category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | linebreaks }}</p>
        <h3>Leave a comment:</h3>
        {% comment %} <form action="/blog/{{ post.pk }}/" method="post"> {% endcomment %}
        <form action="{% url 'blog:blog-detail' post.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.author }}
            </div>
            <div class="form-group">
                {{ form.body }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <h3>Comments:</h3>
        {% if comments %}
            {% for comment in comments %}
            <p>
                On {{comment.date_posted.date }}&nbsp;
                <b>{{ comment.author }}</b> wrote:
            </p>
            <p>{{ comment.body }}</p>
            <hr>
            {% endfor %}
        {% endif %}
    </div>
{% endblock content %}

blog/templates/blog/blog_index.html
{% extends "base.html" %}

{% block title %}
    {{ the_site_name }}
    -
    {{ page_title }}
{% endblock title %}

{% block the_navbar %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'projects:index' %}">Projects</a>
    </li>

    {% if user.is_authenticated %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'profile' user.id %}">Profile</a>
    </li>
    <li class="dropdown-divider"></li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}

{% endblock the_navbar %}

{% block content %}
    <div class="col-md-8 offset-md-2">
        <h1>Bruce Stull's Blog</h1>
        <hr>
        {% for post in posts %}
        <h2><a href="{% url 'blog:blog-detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.date_posted.date }} |&nbsp;
            {{ post.author }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:blog-category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
{% endblock content %}