blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_index, name='index'),
    path('<int:pk>/', views.blog_detail, name='blog-detail'),
    path('<category>/', views.blog_category, name='blog-category'),
]

projects/urls.py
from django.urls import path

from projects import views

app_name = 'projects'
urlpatterns = [
    path('', views.projects, name='index'),
    path('<int:pk>/', views.project, name='project-detail'),
]

projects/models.py
from django.db import models

from config.settings.common import AUTH_USER_MODEL


class Project(models.Model):
    """
    Model for each project.

    An `owner` can have multiple `Project`s.
    """
    title = models.CharField(
        max_length=100,
    )
    description = models.TextField()
    technology = models.CharField(
        max_length=25,
    )
    owner = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    image = models.FilePathField(
        "Image Location",
        path="/images",
    )

    def __str__(self):
        return self.title

projects/views.py
from django.shortcuts import render

from config.settings.common import THE_SITE_NAME
from projects.models import Project


def projects(request):
    """
    View for the `projects.Project` list view.
    """
    projects = Project.objects.all()
    context = {
        'the_site_name': THE_SITE_NAME,
        'page_title': 'Projects',
        'projects': projects,
    }
    return render(request, 'projects/projects.html', context)

def project(request, pk):
    """
    View for the `projects.Project` detail view.
    """
    project = Project.objects.get(pk=pk)
    context = {
        'the_site_name': THE_SITE_NAME,
        'page_title': project.title,
        'project': project,
    }
    return render(request, 'projects/project.html', context)

projects/templates/projects/project.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ the_site_name }}
    -
    {{ page_title }}
{% endblock title %}

{% block the_navbar %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
    </li>

    {% if user.is_authenticated %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'profile' user.id %}">Profile</a>
    </li>
    <li class="dropdown-divider"></li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
    </li>
    {% endif %}

{% endblock the_navbar %}

{% block content %}
    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project:</h5>
            <p>{{ project.description }}</p>
            <br>
            <h5>Technology used:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>
{% endblock content %}

projects/templates/projects/projects.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ the_site_name }}
    -
    {{ page_title }}
{% endblock title %}

{% block the_navbar %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
    </li>

    {% if user.is_authenticated %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'profile' user.id %}">Profile</a>
    </li>
    <li class="dropdown-divider"></li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
    </li>
    {% endif %}

{% endblock the_navbar %}

{% block content %}
    <h1>Projects</h1>
    <div class="row">
        {% for project in projects %}
            <div class="col-md-4">
                <div class="card mb-2">
                    <img class="card-img-top" src="{% static project.image %}">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.title }}</h5>
                        <p class="card-text">{{ project.description | truncatewords:20 }}</p>
                        <a
                            href="{% url 'projects:project-detail' project.pk %}"
                            class="btn btn-primary"
                            >
                            Read More
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}